"""adds indexes

Revision ID: 308ada33f6a8
Revises: d550b000a86d
Create Date: 2024-11-16 11:38:49.140845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '308ada33f6a8'
down_revision: Union[str, None] = 'd550b000a86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_companies_created_at', 'companies', ['created_at'], unique=False)
    op.create_index('ix_projects_company_id', 'projects', ['company_id'], unique=False)
    op.create_index('ix_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_index('ix_subscription_plans_name', 'subscription_plans', ['name'], unique=False)
    op.create_index('ix_subscriptions_company_id', 'subscriptions', ['company_id'], unique=False)
    op.create_index('ix_subscriptions_subscription_plan_id', 'subscriptions', ['subscription_plan_id'], unique=False)
    op.create_index('ix_team_memberships_role_id', 'team_memberships', ['role_id'], unique=False)
    op.create_index('ix_team_memberships_user_company', 'team_memberships', ['user_id', 'company_id'], unique=False)
    op.create_index('ix_test_case_runs_executed_at', 'test_case_runs', ['executed_at'], unique=False)
    op.create_index('ix_test_case_runs_test_case_id', 'test_case_runs', ['test_case_id'], unique=False)
    op.create_index('ix_test_cases_suite_id', 'test_cases', ['suite_id'], unique=False)
    op.create_index('ix_test_suites_project_id', 'test_suites', ['project_id'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_test_suites_project_id', table_name='test_suites')
    op.drop_index('ix_test_cases_suite_id', table_name='test_cases')
    op.drop_index('ix_test_case_runs_test_case_id', table_name='test_case_runs')
    op.drop_index('ix_test_case_runs_executed_at', table_name='test_case_runs')
    op.drop_index('ix_team_memberships_user_company', table_name='team_memberships')
    op.drop_index('ix_team_memberships_role_id', table_name='team_memberships')
    op.drop_index('ix_subscriptions_subscription_plan_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_company_id', table_name='subscriptions')
    op.drop_index('ix_subscription_plans_name', table_name='subscription_plans')
    op.drop_index('ix_role_permissions_role_id', table_name='role_permissions')
    op.drop_index('ix_projects_company_id', table_name='projects')
    op.drop_index('ix_companies_created_at', table_name='companies')
    # ### end Alembic commands ###
